import mongoose from "mongoose";
import dotenv from "dotenv";
import { Product } from "../models/Product.js";
import { applySmartPrice } from "../utils/priceRule.js";

dotenv.config();

const sampleProducts = [
  {
    name: "Sony WH-1000XM5",
    description: "Flagship over-ear wireless headphones with class-leading ANC, LDAC support, and 30-hour battery life.",
    category: "Audio",
    basePrice: 34999,
    images: ["https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=800&auto=format&fit=crop"],
    stock: 28,
    tags: ["headphones", "anc", "wireless"],
  },
  {
    name: "Bose QuietComfort Ultra Earbuds",
    description: "Premium true wireless earbuds with CustomTune calibration, immersive spatial audio, and IPX4 sweat resistance.",
    category: "Audio",
    basePrice: 27999,
    images: ["https://images.unsplash.com/photo-1585386959984-a4155224a1fd?w=800&auto=format&fit=crop"],
    stock: 40,
    tags: ["earbuds", "noise-cancelling", "wireless"],
  },
  {
    name: "Apple AirPods Pro (2nd Gen)",
    description: "H2-powered earbuds with Adaptive Transparency, Personalized Spatial Audio, and MagSafe charging case.",
    category: "Audio",
    basePrice: 24999,
    images: ["https://images.unsplash.com/photo-1585386955907-23fe8e5d0435?w=800&auto=format&fit=crop"],
    stock: 55,
    tags: ["earbuds", "anc", "apple"],
  },
  {
    name: "Apple MacBook Air 13\" M2",
    description: "Fanless 13-inch MacBook Air with M2 chip, 18-hour battery life, and 500-nit Liquid Retina display.",
    category: "Laptops",
    basePrice: 109999,
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop"],
    stock: 22,
    tags: ["laptop", "apple", "ultrabook"],
  },
  {
    name: "Dell XPS 13 Plus (2024)",
    description: "13.4-inch InfinityEdge OLED ultrabook with Intel Core Ultra, zero-lattice keyboard, and glass haptic trackpad.",
    category: "Laptops",
    basePrice: 124999,
    images: ["https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop"],
    stock: 15,
    tags: ["laptop", "windows", "ultrabook"],
  },
  {
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    description: "1.12kg business ultrabook with 14-inch 2.8K OLED, MIL-STD durability, and 12th Gen Intel vPro CPUs.",
    category: "Laptops",
    basePrice: 134999,
    images: ["https://images.unsplash.com/photo-1523473827532-68670ddaf1b9?w=800&auto=format&fit=crop"],
    stock: 18,
    tags: ["laptop", "business", "thinkpad"],
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    description: "6.8-inch AMOLED flagship with Snapdragon 8 Gen 3, 200MP camera, and S Pen built-in.",
    category: "Smartphones",
    basePrice: 129999,
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop"],
    stock: 35,
    tags: ["android", "5g", "camera"],
  },
  {
    name: "Google Pixel 8 Pro",
    description: "6.7-inch LTPO OLED with Google Tensor G3, Pro camera controls, and 7 years of OS updates.",
    category: "Smartphones",
    basePrice: 99999,
    images: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop"],
    stock: 32,
    tags: ["android", "pixel", "camera"],
  },
  {
    name: "iPhone 15 Pro",
    description: "6.1-inch Super Retina XDR with A17 Pro, titanium frame, USB-C, and 3x telephoto camera.",
    category: "Smartphones",
    basePrice: 119999,
    images: ["https://images.unsplash.com/photo-1512499617640-c2f999098c01?w=800&auto=format&fit=crop"],
    stock: 30,
    tags: ["apple", "5g", "flagship"],
  },
  {
    name: "iPad Pro 12.9\" (M2)",
    description: "Mini-LED Liquid Retina XDR tablet with M2 chip, Apple Pencil hover, and ProRes video capture.",
    category: "Tablets",
    basePrice: 124999,
    images: ["https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=800&auto=format&fit=crop"],
    stock: 20,
    tags: ["tablet", "apple", "creative"],
  },
  {
    name: "Kindle Paperwhite (11th Gen)",
    description: "6.8-inch glare-free e-reader with adjustable warm light, USB-C, and 10-week battery life.",
    category: "E-readers",
    basePrice: 14999,
    images: ["https://images.unsplash.com/photo-1523473827532-68670ddaf1b9?w=800&auto=format&fit=crop"],
    stock: 60,
    tags: ["reading", "ebook", "kindle"],
  },
  {
    name: "Nintendo Switch OLED",
    description: "Hybrid console with 7-inch OLED screen, enhanced audio, and 64GB storage for docked or handheld play.",
    category: "Gaming",
    basePrice: 34999,
    images: ["https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop"],
    stock: 25,
    tags: ["console", "gaming", "nintendo"],
  },
  {
    name: "PlayStation 5 Slim",
    description: "4K HDR gaming console with Tempest 3D Audio, DualSense haptics, and ultra-fast SSD load times.",
    category: "Gaming",
    basePrice: 54999,
    images: ["https://images.unsplash.com/photo-1606813902914-06e9f1fa81e9?w=800&auto=format&fit=crop"],
    stock: 22,
    tags: ["console", "sony", "4k"],
  },
  {
    name: "Xbox Series X",
    description: "12 TFLOPS console with 4K/120fps support, Quick Resume, and Dolby Vision gaming.",
    category: "Gaming",
    basePrice: 52999,
    images: ["https://images.unsplash.com/photo-1606813903052-0c4b7c4d5aaa?w=800&auto=format&fit=crop"],
    stock: 24,
    tags: ["console", "microsoft", "4k"],
  },
  {
    name: "LG C3 OLED TV 55\"",
    description: "55-inch 4K OLED evo panel with α9 Gen6 processor, Dolby Vision IQ, and NVIDIA G-SYNC compatibility.",
    category: "TVs",
    basePrice: 159999,
    images: ["https://images.unsplash.com/photo-1582719478171-2f57f69f6a4d?w=800&auto=format&fit=crop"],
    stock: 12,
    tags: ["oled", "home-theater", "4k"],
  },
  {
    name: "Samsung Odyssey G9",
    description: "49-inch 240Hz dual QHD curved gaming monitor with Quantum Mini LED and 1ms response time.",
    category: "Monitors",
    basePrice: 129999,
    images: ["https://images.unsplash.com/photo-1527443224154-d3f02fe5fc8b?w=800&auto=format&fit=crop"],
    stock: 10,
    tags: ["monitor", "gaming", "ultrawide"],
  },
  {
    name: "Asus ROG Zephyrus G14 (2024)",
    description: "14-inch QHD+ 165Hz gaming laptop with AMD Ryzen 9, RTX 4070, and AniMe Matrix lid.",
    category: "Laptops",
    basePrice: 164999,
    images: ["https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop"],
    stock: 14,
    tags: ["gaming", "laptop", "rtx"],
  },
  {
    name: "Razer Blade 15 (2023)",
    description: "15-inch QHD 240Hz laptop with Intel Core i7, RTX 4070 graphics, and CNC aluminum chassis.",
    category: "Laptops",
    basePrice: 199999,
    images: ["https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop"],
    stock: 12,
    tags: ["gaming", "laptop", "razer"],
  },
  {
    name: "Canon EOS R6 Mark II",
    description: "24.2MP full-frame mirrorless camera with 40fps burst, 4K60 oversampled video, and Dual Pixel AF II.",
    category: "Cameras",
    basePrice: 199999,
    images: ["https://images.unsplash.com/photo-1519183071298-a2962be90b8e?w=800&auto=format&fit=crop"],
    stock: 18,
    tags: ["camera", "mirrorless", "canon"],
  },
  {
    name: "Sony A7 IV",
    description: "33MP full-frame mirrorless with 10fps shooting, 4K60 10-bit video, and improved Real-time Tracking AF.",
    category: "Cameras",
    basePrice: 214999,
    images: ["https://images.unsplash.com/photo-1504639725590-34d4982c1b89?w=800&auto=format&fit=crop"],
    stock: 14,
    tags: ["camera", "sony", "full-frame"],
  },
  {
    name: "GoPro Hero12 Black",
    description: "Action camera with 5.3K60 video, HDR across photo and video, and HyperSmooth 6.0 stabilization.",
    category: "Action Cams",
    basePrice: 44999,
    images: ["https://images.unsplash.com/photo-1508896694512-8d3f0f7e06c1?w=800&auto=format&fit=crop"],
    stock: 45,
    tags: ["action-cam", "gopro", "4k"],
  },
  {
    name: "DJI Mini 4 Pro",
    description: "Sub-249g camera drone with 4K60 HDR, omnidirectional obstacle sensing, and 34-minute flights.",
    category: "Drones",
    basePrice: 89999,
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop"],
    stock: 20,
    tags: ["drone", "4k", "dji"],
  },
  {
    name: "Insta360 X3",
    description: "360° action cam with 5.7K HDR video, Active HDR mode, and FlowState stabilization.",
    category: "Action Cams",
    basePrice: 38999,
    images: ["https://images.unsplash.com/photo-1508896694512-8d3f0f7e06c1?w=800&auto=format&fit=crop"],
    stock: 26,
    tags: ["360", "action-cam", "insta360"],
  },
  {
    name: "Fitbit Charge 6",
    description: "Slim fitness tracker with built-in GPS, ECG, and Google Maps notifications on wrist.",
    category: "Wearables",
    basePrice: 18999,
    images: ["https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=800&auto=format&fit=crop"],
    stock: 55,
    tags: ["fitness", "tracker", "fitbit"],
  },
  {
    name: "Garmin Forerunner 965",
    description: "Premium triathlon watch with AMOLED display, dual-band GPS, and wrist-based running dynamics.",
    category: "Wearables",
    basePrice: 69999,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop"],
    stock: 18,
    tags: ["running", "gps", "garmin"],
  },
  {
    name: "Apple Watch Ultra 2",
    description: "49mm titanium smartwatch with dual-frequency GPS, 3,000-nit display, and 36-hour battery life.",
    category: "Wearables",
    basePrice: 89999,
    images: ["https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=800&auto=format&fit=crop"],
    stock: 16,
    tags: ["apple", "smartwatch", "outdoor"],
  },
  {
    name: "Samsung Galaxy Watch6 Classic",
    description: "Rotating-bezel smartwatch with AMOLED display, body composition tracking, and Wear OS 4.",
    category: "Wearables",
    basePrice: 36999,
    images: ["https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=800&auto=format&fit=crop"],
    stock: 30,
    tags: ["samsung", "smartwatch", "wearos"],
  },
  {
    name: "Logitech MX Master 3S",
    description: "Ergonomic wireless mouse with MagSpeed scroll, 8K DPI tracking, and Logi Options+ shortcuts.",
    category: "Peripherals",
    basePrice: 8999,
    images: [
      "https://images.unsplash.com/photo-1587820518895-6401e034bdcc?auto=format&fit=crop&w=1200&q=80",
    ],
    stock: 70,
    tags: ["mouse", "wireless", "productivity"],
  },
  {
    name: "Keychron K4 V2",
    description: "96% wireless mechanical keyboard with hot-swappable switches, Bluetooth 5.1, and white backlight.",
    category: "Peripherals",
    basePrice: 8499,
    images: ["https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&auto=format&fit=crop"],
    stock: 45,
    tags: ["keyboard", "mechanical", "wireless"],
  },
  {
    name: "Corsair K70 RGB Pro",
    description: "Full-size mechanical keyboard with Cherry MX switches, AXON 8,000Hz polling, and PBT keycaps.",
    category: "Peripherals",
    basePrice: 14999,
    images: ["https://images.unsplash.com/photo-1587829191301-dc798b83add3?w=800&auto=format&fit=crop"],
    stock: 30,
    tags: ["keyboard", "gaming", "rgb"],
  },
  {
    name: "Logitech G Pro X Superlight 2",
    description: "58g wireless esports mouse with HERO 2 sensor, 32K DPI, and LIGHTSPEED low-latency tech.",
    category: "Peripherals",
    basePrice: 15499,
    images: [
      "https://images.unsplash.com/photo-1587202372775-98927a357f3d?auto=format&fit=crop&w=1200&q=80",
    ],
    stock: 36,
    tags: ["mouse", "gaming", "wireless"],
  },
  {
    name: "SteelSeries Arctis Nova Pro Wireless",
    description: "Multi-system wireless gaming headset with active noise cancellation and GameDAC Gen 2 base station.",
    category: "Audio",
    basePrice: 32999,
    images: ["https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=800&auto=format&fit=crop"],
    stock: 22,
    tags: ["headset", "gaming", "wireless"],
  },
  {
    name: "Sennheiser Momentum 4",
    description: "Over-ear Bluetooth headphones with 60-hour battery life, aptX Adaptive, and customizable EQ.",
    category: "Audio",
    basePrice: 28999,
    images: ["https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=800&auto=format&fit=crop"],
    stock: 26,
    tags: ["headphones", "wireless", "anc"],
  },
  {
    name: "Sonos Era 300",
    description: "Spatial audio smart speaker with Dolby Atmos, Wi‑Fi 6, Bluetooth, and Trueplay tuning.",
    category: "Speakers",
    basePrice: 54999,
    images: ["https://images.unsplash.com/photo-1459802071246-377c0346da93?w=800&auto=format&fit=crop"],
    stock: 18,
    tags: ["speaker", "smart-home", "dolby"],
  },
  {
    name: "Bose SoundLink Flex",
    description: "Waterproof portable Bluetooth speaker with PositionIQ tuning and up to 12 hours of playtime.",
    category: "Speakers",
    basePrice: 12999,
    images: ["https://images.unsplash.com/photo-1459802071246-377c0346da93?w=800&auto=format&fit=crop"],
    stock: 50,
    tags: ["speaker", "portable", "bluetooth"],
  },
  {
    name: "JBL Charge 5",
    description: "Rugged IP67 Bluetooth speaker with 20-hour battery and powerbank capability for on-the-go charging.",
    category: "Speakers",
    basePrice: 9999,
    images: ["https://images.unsplash.com/photo-1459802071246-377c0346da93?w=800&auto=format&fit=crop"],
    stock: 48,
    tags: ["speaker", "waterproof", "portable"],
  },
  {
    name: "Anker Soundcore Motion X600",
    description: "Hi-Res portable speaker with spatial audio, 50W output, and LDAC support for detailed sound.",
    category: "Speakers",
    basePrice: 15999,
    images: ["https://images.unsplash.com/photo-1459802071246-377c0346da93?w=800&auto=format&fit=crop"],
    stock: 34,
    tags: ["speaker", "ldac", "portable"],
  },
  {
    name: "Philips Hue Starter Kit",
    description: "White and Color Ambiance E26 kit with 3 bulbs, Hue Bridge, and Bluetooth + Zigbee connectivity.",
    category: "Smart Home",
    basePrice: 14999,
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop"],
    stock: 60,
    tags: ["lighting", "smart-home", "zigbee"],
  },
  {
    name: "Nanoleaf Lines Starter Kit",
    description: "Backlit modular light bars with screen mirror, rhythm music sync, and Matter support.",
    category: "Smart Home",
    basePrice: 18999,
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop"],
    stock: 28,
    tags: ["lighting", "rgb", "smart-home"],
  },
  {
    name: "Dyson V15 Detect",
    description: "Cordless vacuum with laser dust detection, piezo sensor particle counts, and up to 60 minutes of run time.",
    category: "Home Appliances",
    basePrice: 65999,
    images: ["https://images.unsplash.com/photo-1501045661006-fcebe0257c3f?w=800&auto=format&fit=crop"],
    stock: 20,
    tags: ["vacuum", "cordless", "home"],
  },
  {
    name: "iRobot Roomba j7+",
    description: "Self-emptying robot vacuum with PrecisionVision navigation and obstacle avoidance for cords and pet waste.",
    category: "Home Appliances",
    basePrice: 79999,
    images: ["https://images.unsplash.com/photo-1523419400523-4391fa21cde1?w=800&auto=format&fit=crop"],
    stock: 18,
    tags: ["robot", "vacuum", "smart-home"],
  },
  {
    name: "Breville Barista Express",
    description: "Stainless steel espresso machine with integrated conical burr grinder and precise 9-bar extraction.",
    category: "Kitchen",
    basePrice: 67999,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop"],
    stock: 14,
    tags: ["espresso", "coffee", "kitchen"],
  },
  {
    name: "KitchenAid Artisan Stand Mixer",
    description: "5-quart tilt-head mixer with 10 speeds, planetary mixing action, and metal construction.",
    category: "Kitchen",
    basePrice: 49999,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop"],
    stock: 16,
    tags: ["baking", "mixer", "kitchen"],
  },
  {
    name: "Vitamix A3500 Blender",
    description: "Ascent Series blender with variable speed, programmable timers, and self-cleaning 64oz jar.",
    category: "Kitchen",
    basePrice: 63999,
    images: ["https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop"],
    stock: 18,
    tags: ["blender", "kitchen", "smoothies"],
  },
  {
    name: "Instant Pot Duo 7-in-1",
    description: "6-quart multi-cooker that pressure cooks, slow cooks, sautés, steams, and makes yogurt.",
    category: "Kitchen",
    basePrice: 12999,
    images: ["https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800&auto=format&fit=crop"],
    stock: 40,
    tags: ["multicooker", "kitchen", "pressure"],
  },
  {
    name: "Ninja Foodi Air Fryer Max XL",
    description: "5.5-quart air fryer with Max Crisp technology for ultra-hot 450°F air to cook faster with less oil.",
    category: "Kitchen",
    basePrice: 15999,
    images: ["https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800&auto=format&fit=crop"],
    stock: 28,
    tags: ["air-fryer", "kitchen", "cooking"],
  },
  {
    name: "Le Creuset Dutch Oven 7.25qt",
    description: "Enameled cast iron round Dutch oven for slow-cooking, braising, and baking with superior heat retention.",
    category: "Kitchen",
    basePrice: 48999,
    images: ["https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800&auto=format&fit=crop"],
    stock: 12,
    tags: ["cookware", "cast-iron", "kitchen"],
  },
  {
    name: "Ooni Koda 16 Pizza Oven",
    description: "Gas-powered outdoor pizza oven reaching 500°C in 20 minutes for 16-inch stone-baked pizzas.",
    category: "Outdoor",
    basePrice: 64999,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop"],
    stock: 10,
    tags: ["pizza", "outdoor", "oven"],
  },
  {
    name: "Yeti Rambler 36oz Bottle",
    description: "Vacuum-insulated stainless steel bottle with Chug Cap, dishwasher safe and leak resistant.",
    category: "Outdoors",
    basePrice: 5499,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop"],
    stock: 80,
    tags: ["hydration", "insulated", "bottle"],
  },
  {
    name: "Hydro Flask Wide Mouth 32oz",
    description: "Double-wall vacuum insulated bottle with Flex Cap, keeps drinks cold up to 24 hours.",
    category: "Outdoors",
    basePrice: 4899,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop"],
    stock: 90,
    tags: ["water-bottle", "insulated", "outdoors"],
  },
  {
    name: "Anker 737 Power Bank (24K)",
    description: "24,000mAh GaN portable charger with 140W two-way PD, smart display, and ActiveShield 2.0 safety.",
    category: "Power",
    basePrice: 14999,
    images: [
      "https://images.unsplash.com/photo-1603791452906-be514cb01acf?auto=format&fit=crop&w=1200&q=80",
    ],
    stock: 65,
    tags: ["powerbank", "usb-c", "gan"],
  },
  {
    name: "Anker 747 GaNPrime 150W Charger",
    description: "4-port GaNPrime desktop charger with two USB-C PD ports delivering up to 100W single-port output.",
    category: "Power",
    basePrice: 9999,
    images: [
      "https://images.unsplash.com/photo-1616448858427-7fef3fa5c9a1?auto=format&fit=crop&w=1200&q=80",
    ],
    stock: 70,
    tags: ["charger", "gan", "usb-c"],
  },
  {
    name: "Samsung T9 Portable SSD 2TB",
    description: "USB 3.2 Gen 2x2 portable SSD with up to 2000MB/s read/write and durable rubberized shell.",
    category: "Storage",
    basePrice: 21999,
    images: [
      "https://images.pexels.com/photos/3945663/pexels-photo-3945663.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    stock: 50,
    tags: ["ssd", "portable", "usb-c"],
  },
  {
    name: "WD Black SN850X 2TB NVMe",
    description: "PCIe 4.0 M.2 NVMe SSD with up to 7,300MB/s reads, Game Mode 2.0, and heatsink option.",
    category: "Storage",
    basePrice: 18999,
    images: [
      "https://images.pexels.com/photos/3945681/pexels-photo-3945681.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    stock: 44,
    tags: ["ssd", "nvme", "pcie4"],
  },
  {
    name: "Seagate One Touch 5TB",
    description: "Compact USB 3.2 external hard drive with Rescue Data Recovery Services and fabric enclosure.",
    category: "Storage",
    basePrice: 11999,
    images: [
      "https://images.pexels.com/photos/3945680/pexels-photo-3945680.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    stock: 60,
    tags: ["hdd", "backup", "portable"],
  },
  {
    name: "Elgato Stream Deck MK.2",
    description: "15-key customizable controller with drag-and-drop actions for streaming, editing, and automation.",
    category: "Peripherals",
    basePrice: 16999,
    images: ["https://images.unsplash.com/photo-1587829191301-dc798b83add3?w=800&auto=format&fit=crop"],
    stock: 25,
    tags: ["streaming", "macro", "creator"],
  },
  {
    name: "Shure SM7B",
    description: "Broadcast dynamic microphone with cardioid pattern, built-in air suspension shock isolation, and presence boost.",
    category: "Audio",
    basePrice: 34999,
    images: ["https://images.unsplash.com/photo-1459802071246-377c0346da93?w=800&auto=format&fit=crop"],
    stock: 18,
    tags: ["microphone", "broadcast", "podcast"],
  },
  {
    name: "LG UltraFine 5K 27\"",
    description: "27-inch 5K IPS monitor with 99% DCI-P3, Thunderbolt 3, and 218 PPI for Mac workflows.",
    category: "Monitors",
    basePrice: 124999,
    images: ["https://images.unsplash.com/photo-1527443224154-d3f02fe5fc8b?w=800&auto=format&fit=crop"],
    stock: 14,
    tags: ["monitor", "5k", "thunderbolt"],
  },
  {
    name: "BenQ PD3220U",
    description: "32-inch 4K Thunderbolt designer monitor with AQCOLOR, factory calibration, and KVM switch.",
    category: "Monitors",
    basePrice: 89999,
    images: ["https://images.unsplash.com/photo-1527443224154-d3f02fe5fc8b?w=800&auto=format&fit=crop"],
    stock: 16,
    tags: ["monitor", "4k", "design"],
  },
  {
    name: "Moft Laptop Stand",
    description: "Ultra-thin adhesive laptop stand with two height options, supports devices up to 17 lbs.",
    category: "Accessories",
    basePrice: 2499,
    images: [
      "https://images.unsplash.com/photo-1481277542470-605612bd2d61?auto=format&fit=crop&w=1200&q=80",
    ],
    stock: 120,
    tags: ["stand", "ergonomics", "portable"],
  },
  {
    name: "Twelve South Curve Flex",
    description: "Adjustable aluminum laptop stand offering 6-11 inch elevation and 0-45° tilt for Macs and PCs.",
    category: "Accessories",
    basePrice: 7499,
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    ],
    stock: 55,
    tags: ["stand", "laptop", "adjustable"],
  },
  {
    name: "Sony ZV-E1",
    description: "Full-frame vlog camera with 12MP sensor, Cinematic Vlog modes, and 4K120 (crop) recording.",
    category: "Cameras",
    basePrice: 229999,
    images: ["https://images.unsplash.com/photo-1504639725590-34d4982c1b89?w=800&auto=format&fit=crop"],
    stock: 12,
    tags: ["camera", "vlogging", "sony"],
  },
];

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected");

    await Product.deleteMany({});
    console.log("Cleared existing products");

    const productsWithPrice = sampleProducts.map((p) => ({
      ...p,
      finalPrice: applySmartPrice(p.basePrice),
    }));

    await Product.insertMany(productsWithPrice);
    console.log(`✓ Seeded ${productsWithPrice.length} products`);

    process.exit(0);
  } catch (err) {
    console.error("Seed failed:", err);
    process.exit(1);
  }
}

seedProducts();
